---
conductarr:
  poll_interval: 15.0

sabnzbd:
  url: http://sabnzbd:8080
  api_key: xxx

radarr:
  url: http://radarr:7878
  api_key: xxx

sonarr:
  url: http://sonarr:8989
  api_key: xxx

queues:
  - name: user_requests
    priority: 100
    matchers:
      - type: tags
        tags: ["request", "overseerr"]

  - name: german_upgrade
    priority: 50
    matchers:
      - type: tags
        tags: ["upgrade-de"]

  - name: kometa
    priority: 10
    enabled: false
    matchers:
      - type: tags
        tags: ["kometa"]
