"""Shared pytest fixtures and hooks."""

from __future__ import annotations

import os
import re
from collections.abc import AsyncGenerator
from pathlib import Path

import pytest
import pytest_asyncio
from dotenv import load_dotenv

from conductarr.clients.sabnzbd import SABnzbdClient

# Load .env from the project root so dev credentials are available without
# having to export variables manually.
load_dotenv(Path(__file__).parent.parent / ".env")

_SABNZBD_INI = Path(__file__).parent.parent / "dev" / "sabnzbd" / "sabnzbd.ini"
_API_KEY_RE = re.compile(r"^api_key\s*=\s*(\w+)", re.MULTILINE)


def _read_api_key_from_ini() -> str | None:
    """Try to extract the api_key from the local SABnzbd config file."""
    if not _SABNZBD_INI.exists():
        return None
    match = _API_KEY_RE.search(_SABNZBD_INI.read_text(encoding="utf-8"))
    return match.group(1) if match else None


@pytest.fixture(scope="session")
def sabnzbd_url() -> str:
    return os.getenv("SABNZBD_URL", "http://localhost:8080")


@pytest.fixture(scope="session")
def sabnzbd_api_key() -> str:
    # 1. explicit env var (CI, .env file, or shell export)
    if key := os.getenv("SABNZBD_API_KEY"):
        return key
    # 2. auto-read from the dev SABnzbd config generated by docker compose
    if key := _read_api_key_from_ini():
        return key
    # 3. fall back to dummy value (unit tests don't need a real key)
    return "testapikey"


@pytest_asyncio.fixture(scope="function")
async def sabnzbd_client(
    sabnzbd_url: str, sabnzbd_api_key: str
) -> AsyncGenerator[SABnzbdClient, None]:
    async with SABnzbdClient(url=sabnzbd_url, api_key=sabnzbd_api_key) as client:
        yield client


def pytest_collection_modifyitems(
    config: pytest.Config, items: list[pytest.Item]
) -> None:
    """Automatically mark every test under tests/integration/ with pytest.mark.integration."""
    integration_mark = pytest.mark.integration
    for item in items:
        if "integration" in str(item.fspath):
            item.add_marker(integration_mark)
